"use client";

import { Bot, MoreHorizontal, Pause, Play, Plus, Settings2, Shield, Sparkles, CheckCircle2, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { ApiAgent, mandateApi, MandatePolicy, Session } from "./lib/mandate-api";

const money = (n:number) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);

export function AgentsLivePage({setView,approvalAll,setApprovalAll,agents,session,refresh}:{setView:(view:"Create Mandate")=>void;approvalAll:boolean;setApprovalAll:(value:boolean)=>void;agents:ApiAgent[];session:Session;refresh:()=>Promise<void>}){
  async function create(){const name=window.prompt("Agent name");if(!name)return;const purpose=window.prompt("What is this agent allowed to purchase?");if(!purpose)return;await mandateApi.createAgent(session.token,{name,purpose});await refresh()}
  async function toggle(agent:ApiAgent){const next=agent.status==="ACTIVE"?"pause":"resume";if(!window.confirm(`${next[0].toUpperCase()+next.slice(1)} ${agent.name}? This changes authorization for all future requests.`))return;await mandateApi.updateAgent(session.token,agent.id,{status:agent.status==="ACTIVE"?"PAUSED":"ACTIVE"});await refresh()}
  function changeApprovalAll(next:boolean){if(next&&!window.confirm("Require human approval for every future transaction? Existing decisions are unchanged."))return;setApprovalAll(next)}
  return <><div className="page-intro"><div><p>{agents.length} agents operate in this workspace.</p><span>Change controls take effect immediately on future requests.</span></div><button className="primary" onClick={()=>void create()}><Plus size={17}/> Create agent</button></div><div className="control-banner card"><div><Shield size={20}/><div><b>Emergency control</b><span>Require human approval for every future agent transaction. Existing decisions are unchanged.</span></div></div><label className="switch"><input aria-label="Require approval for all future transactions" type="checkbox" checked={approvalAll} onChange={e=>changeApprovalAll(e.target.checked)}/><span/></label></div>{agents.length===0?<div className="empty card"><Bot/><h2>Create your first agent</h2><p>Agents receive a mandate and scoped API credentials after creation.</p></div>:<div className="agent-grid">{agents.map((agent,index)=>{const budget=(agent.mandate?.monthlyBudgetCents??0)/100;const spent=Number(agent.spentThisMonthCents)/100;const color=["#6C5CE7","#087F6B","#B86B08","#5846D6"][index%4];return <div className="agent-card card" key={agent.id}><div className="agent-head"><div className="agent-avatar" style={{background:color}}>{agent.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><button className="icon-button" disabled title="Agent menu is planned" aria-label={`More actions for ${agent.name} (planned)`}><MoreHorizontal size={18}/></button></div><h3>{agent.name}</h3><p>{agent.purpose}</p><div className="agent-status"><span className={agent.status!=="ACTIVE"?"paused":""}/>{agent.status[0]+agent.status.slice(1).toLowerCase()}</div><div className="budget-row"><span>Monthly budget</span><b>{money(spent)} <em>/ {money(budget)}</em></b></div><div className="progress" aria-label={`${Math.round(budget?spent/budget*100:0)} percent of budget used`}><i style={{width:`${budget?Math.min(100,spent/budget*100):0}%`,background:color}}/></div><div className="agent-rule"><span>Autonomous limit</span><b>{money((agent.mandate?.maxTransactionCents??0)/100)}</b></div><div className="agent-actions"><button className="secondary" disabled={agent.status==="REVOKED"} onClick={()=>void toggle(agent)}>{agent.status==="ACTIVE"?<Pause size={15}/>:<Play size={15}/>} {agent.status==="ACTIVE"?"Pause":"Resume"}</button><button className="secondary" onClick={()=>setView("Create Mandate")}><Settings2 size={15}/> Edit rules</button></div></div>})}</div>}</>
}

const defaultPolicy:MandatePolicy={monthlyBudgetCents:200000,maxTransactionCents:25000,approvalThresholdCents:25000,allowedCategories:["software","office equipment"],blockedCategories:["crypto","gambling"],allowedMerchants:[],blockedMerchants:[],allowedCountries:["US"],requireApprovalForNewMerchant:true,requireApprovalForAll:false,expiresAt:null};

export function MandateLivePage({agents,session,refresh,text,setText,parsed,setParsed,setView}:{agents:ApiAgent[];session:Session;refresh:()=>Promise<void>;text:string;setText:(value:string)=>void;parsed:boolean;setParsed:(value:boolean)=>void;setView:(view:"Agents")=>void}){
  const [agentId,setAgentId]=useState(agents[0]?.id??""); const [saving,setSaving]=useState(false);
  async function activate(){if(!agentId||!window.confirm("Activate this mandate? It becomes the authority for all future requests from this agent."))return;setSaving(true);try{await mandateApi.createMandate(session.token,agentId,{userIntent:text,policy:defaultPolicy});await refresh();setView("Agents")}finally{setSaving(false)}}
  return <div className="mandate-grid"><section className="card mandate-compose"><div className="step-badge">01</div><span className="kicker">DESCRIBE INTENT</span><h2>Write the spending mandate</h2><p>Use plain language. AI translates your intent into policy; it never authorizes transactions.</p><label>Agent<select value={agentId} onChange={event=>setAgentId(event.target.value)}>{agents.map(agent=><option value={agent.id} key={agent.id}>{agent.name}</option>)}</select></label><label>Mandate instructions<textarea value={text} onChange={event=>setText(event.target.value)} rows={10}/></label><button className="primary full" disabled={!agentId} onClick={()=>setParsed(true)}><Sparkles size={17}/> Interpret mandate</button></section><section className={`card policy-preview ${parsed?"ready":""}`}><div className="step-badge">02</div><span className="kicker">STRUCTURED POLICY</span><h2>Review deterministic rules</h2>{!parsed?<div className="empty"><SlidersHorizontal size={32}/><p>Your structured policy will appear here for review.</p></div>:<><div className="llm-boundary"><Sparkles size={17}/><div><b>Interpretation ready for review</b><span>Activation persists a versioned policy to PostgreSQL.</span></div></div><pre>{JSON.stringify(defaultPolicy,null,2)}</pre><div className="policy-check"><CheckCircle2 size={17}/><span>Schema valid · deterministic rules</span></div><button className="primary full" disabled={saving} onClick={()=>void activate()}><Shield size={17}/> {saving?"Activating…":"Activate mandate"}</button></>}</section></div>
}
