import type { Metadata } from "next";
import { ArticleShell } from "../../resource-shell";
import { BLOG_AUTHOR } from "../posts";

const canonical = "/blog/how-to-set-spending-limits-for-ai-agents";

export const metadata: Metadata = {
  title: "How to Set Spending Limits for AI Agents",
  description: "Learn how to set AI-agent spending limits with budgets, transaction caps, merchant rules, approvals, expiration, and emergency controls.",
  alternates: { canonical },
  authors: [{ name: BLOG_AUTHOR }],
  openGraph: { type: "article", url: canonical, title: "How to set spending limits for AI agents", description: "A practical framework for limiting what an AI agent may buy, when it needs review, and how its authority ends.", publishedTime: "2026-08-15", authors: [BLOG_AUTHOR] },
};

export default function SpendingLimitsPost() {
  return (
    <ArticleShell section="Blog" title="How to set spending limits for AI agents." description="A useful spending limit is not one number. It is a small authority envelope that defines who may request, what they may buy, how much they may spend, and when a person must intervene." date="August 15, 2026" datePublished="2026-08-15" canonical={canonical} author={BLOG_AUTHOR} readingTime="11 minute read" related={[
      { href: "/blog/what-is-an-ai-agent-payment-mandate", title: "What is an AI-agent payment mandate?", description: "Understand the control object that holds these limits.", type: "Explainer" },
      { href: "/learn/agentic-commerce", title: "The agentic commerce field guide", description: "Follow a request from human intent through authorization evidence.", type: "Field guide" },
      { href: "/knowledge#mandates", title: "Spending mandates", description: "Review the fields used in Mandate’s current model.", type: "Knowledge" },
    ]}>
      <section className="article-summary"><h2>The short version</h2><p><strong>Start with a narrow job, a monthly ceiling, a smaller autonomous transaction cap, and explicit review conditions.</strong> Then add merchant, category, geography, time, and lifecycle controls. Test representative purchases before activation, and make pause and revoke immediately available.</p></section>
      <section><h2>Begin with the agent’s job, not its budget</h2><p>A budget without a purpose is only a larger blast radius. Before choosing a dollar amount, write down the job the agent is expected to perform. “Procurement agent” is still broad. “Renew approved software subscriptions and order routine office supplies for the San Francisco team” gives the policy designer something concrete to constrain.</p><p>The purpose should guide every later field. A software-renewal agent probably needs recurring SaaS merchants and a narrow software category. A travel-booking agent needs airlines and hotels, different transaction amounts, and more geographic flexibility. Combining those jobs into one identity makes the policy harder to understand and the audit trail harder to defend.</p><p>When two jobs need materially different permissions, create two agents. Least privilege is easier to maintain when authority follows a clear operational role.</p></section>
      <section><h2>Separate monthly budget from autonomous authority</h2><p>The monthly budget answers how much the agent may consume during a budget period. The maximum autonomous transaction answers how large one request may be before a person reviews it. They should not be the same number.</p><p>Suppose a procurement agent has a $2,000 monthly budget. A $2,000 autonomous limit would allow the entire budget to leave in one request. A $250 autonomous limit lets the agent handle ordinary renewals while escalating an $899 laptop. The remaining budget still matters: an otherwise valid $96 request should decline if only $40 remains.</p><p>A practical starting point is to review recent human-approved purchases for the job. Set the monthly ceiling near the legitimate operating need, not the largest imaginable emergency. Set the autonomous cap around the upper edge of routine purchases. Exceptional spending belongs in a review path, not inside everyday authority.</p></section>
      <section><h2>Use an approval threshold for ambiguity</h2><p>Amount is not the only reason to ask a person. A request can fit under the transaction cap and still deserve review because the merchant is new, the category is adjacent to the agent’s purpose, or the geography is unusual.</p><p>Think of approval conditions as deliberate friction. They preserve speed for known, repeatable work and create a checkpoint when context matters. Common conditions include every new merchant, any transaction above a threshold, every international request, unusually rapid purchase attempts, and any category outside a tight allowlist.</p><p>Do not confuse approval with a soft decline. A blocked category such as gambling or cryptocurrency should remain declined. If the business intends to permit an exception, an operator should deliberately change the mandate and submit a new request. That preserves evidence that the old authority did not allow it.</p></section>
      <section><h2>Prefer allowlists for narrow jobs</h2><p>There are two basic ways to express scope. An allowlist says which merchants, categories, or countries are eligible. A blocklist names known prohibitions. For a narrowly defined agent, allowlists usually provide a clearer boundary because everything outside the expected job starts in a restricted state.</p><p>A software-renewal agent might allow software and cloud infrastructure, allow Notion and AWS, require review for other merchants, and limit countries to the United States. A general operations agent may need broader categories but can still block crypto, gambling, cash equivalents, gift cards, and known risky merchants.</p><p>Merchant names require normalization in production. “Amazon,” “Amazon Web Services,” and a payment descriptor may represent different business relationships. Category data may also be incomplete or disputed. Treat uncertain classification as a reason for review, not a reason to silently infer permission.</p></section>
      <section><h2>Add time and lifecycle boundaries</h2><p>Authority should not last forever by default. Mandates can expire at the end of a project, contract, travel window, or fiscal period. Temporary agents should receive temporary authority. Permanent agents still need periodic review.</p><p>Status is a separate control. Pausing an agent should stop new requests without erasing its history. Revoking it should end the relationship and invalidate credentials. Requiring approval for all future transactions is a useful intermediate state when behavior looks suspicious but the operator still needs visibility into attempted work.</p><p>Budget changes and threshold changes should create new mandate versions. Historical transactions must continue pointing to the version evaluated at request time. Without versioning, today’s settings can misleadingly appear to justify yesterday’s decision.</p></section>
      <section><h2>Model a complete authority envelope</h2><div className="article-table-wrap"><table><thead><tr><th>Control</th><th>Question it answers</th><th>Example</th></tr></thead><tbody><tr><td>Agent identity</td><td>Who is requesting?</td><td>Procurement agent</td></tr><tr><td>Monthly budget</td><td>How much may it consume this period?</td><td>$2,000</td></tr><tr><td>Autonomous maximum</td><td>How large can one request be without review?</td><td>$250</td></tr><tr><td>Approval conditions</td><td>When must a person decide?</td><td>Every new merchant</td></tr><tr><td>Allowed scope</td><td>What is eligible?</td><td>Software and office equipment</td></tr><tr><td>Blocked scope</td><td>What is never eligible?</td><td>Crypto and gambling</td></tr><tr><td>Geography</td><td>Where may the transaction occur?</td><td>United States</td></tr><tr><td>Expiration</td><td>When does authority end?</td><td>End of quarter</td></tr></tbody></table></div><p>The fields should be stored as typed data, not only as prose. Natural-language instructions are helpful for drafting, but the activated version must be inspectable and deterministic.</p></section>
      <section><h2>Test the policy before activation</h2><p>Create a small test suite from realistic purchases. For the example procurement agent, try Notion at $96, AWS at $212, Apple at $899, Binance at $600, and a second Notion request after most of the budget has been consumed.</p><p>For each scenario, predict the result before running it. Notion may be approved because it is known, allowed, and below the autonomous cap. AWS may be approved under the same logic. Apple should require review because the amount is high or the merchant is new. Binance should decline because crypto is blocked. A later Notion renewal should decline if it exceeds the remaining budget.</p><p>Inspect the rule evidence, not just the final state. A correct-looking outcome can still be produced for the wrong reason. The trace should identify the agent, mandate version, budget snapshot, merchant status, category result, country result, risk factors, and final decision.</p></section>
      <section><h2>Design the human review moment</h2><p>An approval queue should show enough evidence to decide without forcing the reviewer to reconstruct the policy. Include the amount, merchant history, remaining budget after approval, exact review-triggering rules, risk factors, and the scope of the action.</p><p>“Approve once” should resolve one request. It should not quietly add the merchant to an allowlist or raise the agent’s threshold. If the reviewer wants a durable policy change, that should be a separate, versioned action. Decline should also preserve the original request and the reviewer’s note.</p><p>After resolution, the item should leave the pending queue, appear in the transaction history, and append a human-resolution audit event. The interface should provide a receipt rather than leaving a stale error banner or inviting a second resolution attempt.</p></section>
      <section><h2>Monitor limits as the business changes</h2><p>Limits are not set-and-forget configuration. Review requests that repeatedly require approval, merchants that become routine, categories that are never used, and agents that consistently approach their budgets. The goal is not to maximize autonomous approvals. It is to make the smallest safe authority envelope fit the actual job.</p><p>Watch for changes in transaction velocity, amount distribution, geography, and merchant novelty. Risk signals can make an eligible request more restrictive, but they should never turn an explicitly blocked request into an approval. Read <a href="/blog/risk-scores-should-not-override-policy">why risk scores should not override policy</a> for the reasoning behind that one-way relationship.</p></section>
      <section><h2>A practical activation checklist</h2><ol><li>Give the agent one specific operational purpose.</li><li>Choose a monthly budget based on legitimate recurring need.</li><li>Set a much smaller autonomous transaction maximum.</li><li>Allow only the categories, merchants, and countries the job requires.</li><li>Block categories the business will not delegate.</li><li>Require review for new merchants and ambiguous cases.</li><li>Add an expiration or scheduled review date.</li><li>Test ordinary, exceptional, prohibited, and exhausted-budget scenarios.</li><li>Confirm pause, revoke, and approval-for-all controls work.</li><li>Activate one version and preserve every later change as a new version.</li></ol><p>Mandate’s simulator models this workflow without moving money. The important production principle is portable: authority should be explicit, narrow, testable, revocable, and separate from the agent asking to use it.</p></section>
    </ArticleShell>
  );
}
