import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const timestamps={createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()};

export const users=sqliteTable("users",{id:text("id").primaryKey(),email:text("email").notNull().unique(),fullName:text("full_name"),...timestamps});
export const agents=sqliteTable("agents",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>users.id),name:text("name").notNull(),purpose:text("purpose").notNull(),status:text("status",{enum:["active","paused","revoked"]}).notNull(),monthlyBudgetCents:integer("monthly_budget_cents").notNull(),spentThisMonthCents:integer("spent_this_month_cents").notNull().default(0),requireAllApproval:integer("require_all_approval",{mode:"boolean"}).notNull().default(false),...timestamps});
export const mandates=sqliteTable("mandates",{id:text("id").primaryKey(),agentId:text("agent_id").notNull().references(()=>agents.id),intentText:text("intent_text").notNull(),version:integer("version").notNull(),status:text("status",{enum:["draft","active","expired","revoked"]}).notNull(),currency:text("currency").notNull(),monthlyBudgetCents:integer("monthly_budget_cents").notNull(),maxAutonomousCents:integer("max_autonomous_cents").notNull(),approvalThresholdCents:integer("approval_threshold_cents").notNull(),allowedCategoriesJson:text("allowed_categories_json").notNull(),blockedCategoriesJson:text("blocked_categories_json").notNull(),allowedMerchantsJson:text("allowed_merchants_json").notNull(),blockedMerchantsJson:text("blocked_merchants_json").notNull(),allowedCountriesJson:text("allowed_countries_json").notNull(),newMerchantRequiresApproval:integer("new_merchant_requires_approval",{mode:"boolean"}).notNull(),expiresAt:text("expires_at"),...timestamps});
export const transactions=sqliteTable("transactions",{id:text("id").primaryKey(),agentId:text("agent_id").notNull().references(()=>agents.id),mandateId:text("mandate_id").notNull().references(()=>mandates.id),merchant:text("merchant").notNull(),merchantCategory:text("merchant_category").notNull(),country:text("country").notNull(),currency:text("currency").notNull(),amountCents:integer("amount_cents").notNull(),isNewMerchant:integer("is_new_merchant",{mode:"boolean"}).notNull(),idempotencyKey:text("idempotency_key").notNull().unique(),requestedAt:text("requested_at").notNull(),metadataJson:text("metadata_json").notNull()});
export const authorizationDecisions=sqliteTable("authorization_decisions",{id:text("id").primaryKey(),transactionId:text("transaction_id").notNull().unique().references(()=>transactions.id),decision:text("decision",{enum:["APPROVED","APPROVAL_REQUIRED","DECLINED"]}).notNull(),reasonCodesJson:text("reason_codes_json").notNull(),ruleResultsJson:text("rule_results_json").notNull(),policyVersion:integer("policy_version").notNull(),riskScore:integer("risk_score").notNull(),riskFactorsJson:text("risk_factors_json").notNull(),decidedAt:text("decided_at").notNull()});
export const approvalRequests=sqliteTable("approval_requests",{id:text("id").primaryKey(),transactionId:text("transaction_id").notNull().unique().references(()=>transactions.id),status:text("status",{enum:["pending","approved","declined","expired"]}).notNull(),reviewerUserId:text("reviewer_user_id").references(()=>users.id),reviewNote:text("review_note"),resolvedAt:text("resolved_at"),createdAt:text("created_at").notNull()});
export const auditEvents=sqliteTable("audit_events",{id:text("id").primaryKey(),userId:text("user_id").references(()=>users.id),agentId:text("agent_id").references(()=>agents.id),transactionId:text("transaction_id").references(()=>transactions.id),eventType:text("event_type").notNull(),actorType:text("actor_type",{enum:["user","agent","system"]}).notNull(),payloadJson:text("payload_json").notNull(),previousHash:text("previous_hash"),eventHash:text("event_hash").notNull(),occurredAt:text("occurred_at").notNull()});
