import { bigint, boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { MandatePolicy, RiskResult, RuleResult } from "./domain.js";

export const agentStatus = pgEnum("agent_status", ["ACTIVE", "PAUSED", "REVOKED"]);
export const decisionStatus = pgEnum("decision_status", ["APPROVED", "APPROVAL_REQUIRED", "DECLINED"]);
export const approvalStatus = pgEnum("approval_status", ["PENDING", "APPROVED", "DECLINED", "EXPIRED"]);

export const organizations = pgTable("organizations", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), slug: text("slug").notNull().unique(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), name: text("name").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const memberships = pgTable("organization_members", { organizationId: uuid("organization_id").notNull().references(() => organizations.id), userId: uuid("user_id").notNull().references(() => users.id), role: text("role").notNull().default("owner") }, t => [uniqueIndex("membership_unique").on(t.organizationId, t.userId)]);
export const agents = pgTable("agents", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), purpose: text("purpose").notNull(), status: agentStatus("status").notNull().default("ACTIVE"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => [index("agents_org_idx").on(t.organizationId)]);
export const apiKeys = pgTable("agent_api_keys", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), agentId: uuid("agent_id").notNull().references(() => agents.id), name: text("name").notNull(), prefix: text("prefix").notNull(), keyHash: text("key_hash").notNull().unique(), scopes: text("scopes").array().notNull(), lastUsedAt: timestamp("last_used_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const mandates = pgTable("mandates", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), agentId: uuid("agent_id").notNull().references(() => agents.id), version: integer("version").notNull(), userIntent: text("user_intent").notNull(), policy: jsonb("policy").$type<MandatePolicy>().notNull(), active: boolean("active").notNull().default(true), createdBy: uuid("created_by").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => [uniqueIndex("mandate_agent_version_unique").on(t.agentId, t.version)]);
export const transactions = pgTable("transactions", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), agentId: uuid("agent_id").notNull().references(() => agents.id), idempotencyKey: text("idempotency_key").notNull(), merchant: text("merchant").notNull(), category: text("category").notNull(), country: text("country").notNull(), currency: text("currency").notNull().default("USD"), amountCents: bigint("amount_cents", { mode: "number" }).notNull(), metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => [uniqueIndex("transaction_idempotency_unique").on(t.agentId, t.idempotencyKey), index("transactions_org_created_idx").on(t.organizationId, t.createdAt)]);
export const authorizationDecisions = pgTable("authorization_decisions", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), transactionId: uuid("transaction_id").notNull().references(() => transactions.id).unique(), mandateId: uuid("mandate_id").notNull().references(() => mandates.id), decision: decisionStatus("decision").notNull(), policyRules: jsonb("policy_rules").$type<RuleResult[]>().notNull(), reasons: text("reasons").array().notNull(), riskScore: integer("risk_score").notNull(), riskFactors: jsonb("risk_factors").$type<RiskResult["factors"]>().notNull(), engineVersion: text("engine_version").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const approvalRequests = pgTable("approval_requests", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), decisionId: uuid("decision_id").notNull().references(() => authorizationDecisions.id).unique(), status: approvalStatus("status").notNull().default("PENDING"), resolvedBy: uuid("resolved_by").references(() => users.id), resolutionNote: text("resolution_note"), resolvedAt: timestamp("resolved_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const budgetLedger = pgTable("budget_ledger_entries", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), agentId: uuid("agent_id").notNull().references(() => agents.id), transactionId: uuid("transaction_id").notNull().references(() => transactions.id).unique(), amountCents: bigint("amount_cents", { mode: "number" }).notNull(), kind: text("kind").notNull(), period: text("period").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => [index("budget_agent_period_idx").on(t.agentId, t.period)]);
export const auditEvents = pgTable("audit_events", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), sequence: bigint("sequence", { mode: "number" }).notNull(), eventType: text("event_type").notNull(), actorType: text("actor_type").notNull(), actorId: text("actor_id").notNull(), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), previousHash: text("previous_hash"), eventHash: text("event_hash").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, t => [uniqueIndex("audit_org_sequence_unique").on(t.organizationId, t.sequence)]);
